/*---------------------actions-types siigo ----------------------------------*/

export const CREATE_CUSTOMER_SIIGO = 'CREATE_CUSTOMER_SIIGO';
export const GET_CUSTOMERS_SIIGO = 'GET_CUSTOMERS_SIIGO';
export const CLEAN_CUSTOMERS_SIIGO = 'CLEAN_CUSTOMERS_SIIGO';
export const GET_CUSTOMER_BY_ID = 'GET_CUSTOMER_BY_ID';
export const CLEAN_CUSTOMER_BY_ID = 'CLEAN_CUSTOMER_BY_ID';
export const CUSTOMER_DETAILS_REQUEST = 'CUSTOMER_DETAILS_REQUEST';
export const CUSTOMER_DETAILS_SUCCESS = 'CUSTOMER_DETAILS_SUCCESS';
export const CUSTOMER_DETAILS_FAIL = 'CUSTOMER_DETAILS_FAIL';
export const PUT_CUSTOMER_SIIGO = 'PUT_CUSTOMER_SIIGO';
export const GET_ACCOUNT_GROUP = 'GET_ACCOUNT_GROUP';
export const CLEAN_ACCOUNT_GROUP = 'CLEAN_ACCOUNT_GROUP';
export const GET_TAXES = 'GET_TAXES';
export const CLEAN_TAXES = 'CLEAN_TAXES';
export const CREATE_PRODUCT_SIIGO = 'CREATE_PRODUCT_SIIGO';
export const GET_PRODUCT_SIIGO_BY_ID = 'GET_PRODUCT_BY_ID';
export const CLEAN_PRODUCT_BY_ID = 'CLEAN_PRODUCT_BY_ID';
export const GET_PRODUCTS_SIIGO = 'GET_PRODUCTS_SIIGO';
export const CLEAN_PRODUCTS_SIIGO = 'CLEAN_PRODUCTS_SIIGO';
export const PUT_PRODUCT_SIIGO = 'PUT_PRODUCT_SIIGO';
export const DELETE_PRODUCT_BY_ID = 'DELETE_PRODUCT_BY_ID';
export const GET_TYPE_INVOICE = 'GET_TYPE_INVOICE';
export const CLEAN_TYPE_INVOICE = 'CLEAN_TYPE_INVOICE';
export const GET_USERS_SIIGO = 'GET_USERS_SIIGO';
export const CLEAN_USERS_SIIGO = 'CLEAN_USERS_SIIGO';
export const GET_PAYMENTS_TYPE_SIIGO = 'GET_PAYMENTS_TYPE_SIIGO';
export const CLEAN_PAYMENTS_TYPE_SIIGO = 'CLEAN_PAYMENTS_TYPE_SIIGO';
export const GET_INVOICE_BY_ID = 'GET_INVOICE_BY_ID';
export const CLEAN_INVOICE_BY_ID = 'CLEAN_INVOICE_BY_ID';
export const CLEAN_CUSTOMER_DETAIL = 'CLEAN_CUSTOMER_DETAIL';
export const POST_GENERATE_INVOICE = 'POST_GENERATE_INVOICE';
export const GET_COST_CENTER_SIIGO = 'GET_COST_CENTER_SIIGO';
export const CLEAN_COST_CENTER_SIIGO = 'CLEAN_COST_CENTER_SIIGO';

