const { catchedAsync } = require('../utils');
module.exports = {
  createUser: catchedAsync(require('./createUser')),
  auth: catchedAsync(require('./auth')),
  getProducts: catchedAsync(require('./getProducts')),
  getProduct: catchedAsync(require('./getProduct')),
  addProductsCart: catchedAsync(require('./addProductsCart')),
  putUserAdmin: catchedAsync(require('./putUserAdmin')),
  getCartItems: catchedAsync(require('./getCartItems')),
  removeProductCart: catchedAsync(require('./removeProductCart')),
  deleteProductCart: catchedAsync(require('./deleteProductCart')),
  postOrders: catchedAsync(require('./postOrders')),
  destroyCartItemsForUser: catchedAsync(require('./destroyCartItemsForUser')),
  getOrdersUser: catchedAsync(require('./getOrdersUser')),
  getOrderById: catchedAsync(require('./getOrderById')),
  getUsersAdmin: catchedAsync(require('./getUsersAdmin')),
  getCustomersAdmin: catchedAsync(require('./getCustomersAdmin')),
  getUsersAdminOrders: catchedAsync(require('./getUsersAdminOrders')),
  putOrderPaymentResult: catchedAsync(require('./putOrderPaymentResult')),
  putProductAdmin: catchedAsync(require('./putProductAdmin')),
  putProductStatusAdmin: catchedAsync(require('./putProductStatusAdmin')),
  getProductsAdmin: catchedAsync(require('./getProductsAdmin')),
  postNewProduct: catchedAsync(require('./postNewProduct')),
  postEvents: catchedAsync(require('./postEvents')),
  getStores: catchedAsync(require('./getStores')),
  postAssignStockStore: catchedAsync(require('./postAssignStockStore')),
  postAssignCasherStore: catchedAsync(require('./postAssignCasherStore')),
  putOrderDelivery: catchedAsync(require('./putOrderDelivery')),
  getPartners: catchedAsync(require('./getPartners')),
  getPartnersAdmin: catchedAsync(require('./getPartnersAdmin')),
  putPartnerStatusAdmin: catchedAsync(require('./putPartnerStatusAdmin')),
  putPartnerAdmin: catchedAsync(require('./putPartnerAdmin')),
  postNewPartner: catchedAsync(require('./postNewPartner')),
};

//exportamos como una propiedad de lo que exporta  modulo  indexjs
